# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build on Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive

    - name: Configure CMake
      run: cmake --preset default

    - name: Build
      run: cmake --build --preset default
